### ISSUE TITLE
Local Registering Error

### ISSUE THREAD

**Issue by BrandonCate95** [acsysio/acsys#13]
System: Windows 10
Running in google chrome browser

Steps to reproduce:
run 'npm install'
run 'npm run dev'
Cleared Cache in chrome
Open browser at 'http://localhost:80'
page initially shows Sign In with username / password then refreshes with register page
on register page enter in:
email: brandoncate95@gmail.com
username: brandoncate95
password: password
confirm password: password
click on the register button
Displays error: 'Getting metadata from plugin failed with error: invalid_grant'

Stack Trace:
{ Error: 400 undefined: Getting metadata from plugin failed with error: invalid_grant
[1]     at Object.callErrorFromStatus (C:\xampp\htdocs\prometheus\node_modules\@grpc\grpc-js\build\src\call.js:30:26)
[1]     at Object.onReceiveStatus (C:\xampp\htdocs\prometheus\node_modules\@grpc\grpc-js\build\src\client.js:175:52)
[1]     at Object.onReceiveStatus (C:\xampp\htdocs\prometheus\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:341:141)
[1]     at Object.onReceiveStatus (C:\xampp\htdocs\prometheus\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:304:181)
[1]     at Http2CallStream.outputStatus (C:\xampp\htdocs\prometheus\node_modules\@grpc\grpc-js\build\src\call-stream.js:116:74)
[1]     at Http2CallStream.maybeOutputStatus (C:\xampp\htdocs\prometheus\node_modules\@grpc\grpc-js\build\src\call-stream.js:155:22)
[1]     at Http2CallStream.endCall (C:\xampp\htdocs\prometheus\node_modules\@grpc\grpc-js\build\src\call-stream.js:141:18)
[1]     at Http2CallStream.cancelWithStatus (C:\xampp\htdocs\prometheus\node_modules\@grpc\grpc-js\build\src\call-stream.js:457:14)
[1]     at callStream.filterStack.sendMetadata.then (C:\xampp\htdocs\prometheus\node_modules\@grpc\grpc-js\build\src\channel.js:225:36)
[1]     at process._tickCallback (internal/process/next_tick.js:68:7)
[1] Caused by: Error
[1]     at WriteBatch.commit (C:\xampp\htdocs\prometheus\node_modules\@google-cloud\firestore\build\src\write-batch.js:415:23)
[1]     at DocumentReference.create (C:\xampp\htdocs\prometheus\node_modules\@google-cloud\firestore\build\src\reference.js:283:14)
[1]     at CollectionReference.add (C:\xampp\htdocs\prometheus\node_modules\@google-cloud\firestore\build\src\reference.js:2011:28)
[1]     at Promise (C:\xampp\htdocs\prometheus\server\db.js:438:10)
[1]     at new Promise (<anonymous>)
[1]     at DataDriver.insert (C:\xampp\htdocs\prometheus\server\db.js:436:12)
[1]     at C:\xampp\htdocs\prometheus\server\routes\index.js:84:14
[1]   code: '400',
[1]   details:
[1]    'Getting metadata from plugin failed with error: invalid_grant',
[1]   metadata: Metadata { internalRepr: Map {}, options: {} },
[1]   note:
[1]    'Exception occurred in retry method that was not classified as transient' }
[1] (node:8452) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
[1]     at ServerResponse.setHeader (_http_outgoing.js:470:11)
[1]     at ServerResponse.header (C:\xampp\htdocs\prometheus\node_modules\express\lib\response.js:771:10)
[1]     at ServerResponse.send (C:\xampp\htdocs\prometheus\node_modules\express\lib\response.js:170:12)
[1]     at ServerResponse.json (C:\xampp\htdocs\prometheus\node_modules\express\lib\response.js:267:15)
[1]     at ServerResponse.send (C:\xampp\htdocs\prometheus\node_modules\express\lib\response.js:158:21)
[1]     at data.insert.then.catch (C:\xampp\htdocs\prometheus\server\routes\index.js:101:19)
[1] (node:8452) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
[1] (node:8452) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Let me know if you need more info

**Comment by cbridges1** [comment]
Hi @BrandonCate95, executing 'npm run dev' should open a browser window at 'http://localhost:3000'. Have you tried executing 'npm run start' before accessing 'http://localhost:80'?

**Comment by cbridges1** [comment]
Hi @BrandonCate95 we were abel to replicate your issue. A fix is being implemented. Let us know if the next release resolves your issue.
